#!/usr/bin/env node
/**
 * Validate the catJS port against ground-truth catR output.
 *
 * Reads reference/catr_reference.json (generated by scripts/generate_reference.R
 * using the REAL R catR package) and replays every simulated step with the JS
 * port, comparing:
 *   - ability estimate   (thetaEst / EAP)       -> theta
 *   - standard error     (semTheta / EAP)       -> se
 *   - item information   (Ii at theta_used)     -> info vector
 *   - item selection     (nextItem / MFI)       -> selected item (tie-aware)
 *
 * Usage: node scripts/validate.mjs
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  pi,
  ii,
  thetaEst,
  semTheta,
  nextItem,
  estimateTheta,
} from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const refPath = join(__dirname, '..', 'reference', 'catr_reference.json');

const ref = JSON.parse(readFileSync(refPath, 'utf8'));
const bank = ref.itembank.map(([a, b, c, d]) => ({ a, b, c, d }));

const TOL = 1e-9; // absolute tolerance for theta / se / info

// jsonlite with auto_unbox unboxes length-1 vectors into scalars; normalize.
const toArray = (v) => (Array.isArray(v) ? v : [v]);

let nTheta = 0;
let nSe = 0;
let nInfo = 0;
let nSelect = 0;
let maxThetaDiff = 0;
let maxSeDiff = 0;
let maxInfoDiff = 0;
let selectionMismatch = 0;

for (const run of ref.runs) {
  for (const step of run.steps) {
    const administered = toArray(step.administered0);
    const responses = toArray(step.responses);

    // --- 1) Ability estimate + SE after this step
    const { theta, se } = estimateTheta(bank, administered, responses, {
      method: 'EAP',
    });
    const dTheta = Math.abs(theta - step.theta);
    const dSe = Math.abs(se - step.se);
    maxThetaDiff = Math.max(maxThetaDiff, dTheta);
    maxSeDiff = Math.max(maxSeDiff, dSe);
    nTheta++;
    nSe++;
    if (dTheta > TOL) {
      console.error(
        `  THETA MISMATCH run tt=${step.true_theta} step=${step.step}: ` +
          `catR=${step.theta} js=${theta} diff=${dTheta}`,
      );
    }
    if (dSe > TOL) {
      console.error(
        `  SE MISMATCH run tt=${step.true_theta} step=${step.step}: ` +
          `catR=${step.se} js=${se} diff=${dSe}`,
      );
    }

    // --- 2) Item information at theta_used (deterministic, exact-ish)
    const infoJs = bank.map((item) => ii(step.theta_used, item).Ii);
    for (let i = 0; i < infoJs.length; i++) {
      const d = Math.abs(infoJs[i] - step.info[i]);
      maxInfoDiff = Math.max(maxInfoDiff, d);
      nInfo++;
      if (d > TOL) {
        console.error(
          `  INFO MISMATCH run tt=${step.true_theta} step=${step.step} item=${i}: ` +
            `catR=${step.info[i]} js=${infoJs[i]} diff=${d}`,
        );
      }
    }

    // --- 3) Item selection (tie-aware: catR samples among max-info ties)
    const administeredBefore = administered.slice(0, administered.length - 1);
    const res = nextItem(bank, step.theta_used, administeredBefore, {
      criterion: 'MFI',
    });
    // The JS selection must be tied at the max info, and the catR selection
    // must also be in that tie set (catR picks randomly among ties).
    const infoBefore = bank.map((item) => ii(step.theta_used, item).Ii);
    const eligible = [];
    for (let i = 0; i < bank.length; i++) {
      if (!administeredBefore.includes(i)) eligible.push(i);
    }
    const maxInfo = Math.max(...eligible.map((i) => infoBefore[i]));
    const tieSet = eligible.filter((i) => infoBefore[i] === maxInfo);
    const catRInTie = tieSet.includes(step.selected0);
    const jsInTie = tieSet.includes(res.item);
    nSelect++;
    if (!catRInTie || !jsInTie || res.info !== infoBefore[res.item]) {
      selectionMismatch++;
      console.error(
        `  SELECTION MISMATCH run tt=${step.true_theta} step=${step.step}: ` +
          `catR=${step.selected0} js=${res.item} tieSet=[${tieSet}] ` +
          `catRinTie=${catRInTie} jsInTie=${jsInTie}`,
      );
    }
  }
}

console.log('\n=== catJS vs catR validation ===');
console.log(`R version      : ${ref.r_version}`);
console.log(`catR version   : ${ref.catr_version}`);
console.log(`item bank      : ${ref.n_items} items`);
console.log(`runs x steps   : ${ref.runs.length} x ${ref.runs[0].steps.length}`);
console.log('---');
console.log(`theta   : compared ${nTheta}, max |diff| = ${maxThetaDiff.toExponential(3)}`);
console.log(`se      : compared ${nSe}, max |diff| = ${maxSeDiff.toExponential(3)}`);
console.log(`info    : compared ${nInfo}, max |diff| = ${maxInfoDiff.toExponential(3)}`);
console.log(`select  : compared ${nSelect}, mismatches = ${selectionMismatch}`);

const tolOk = maxThetaDiff <= TOL && maxSeDiff <= TOL && maxInfoDiff <= TOL;
const selOk = selectionMismatch === 0;
console.log('---');
console.log(`theta/se/info within tol=${TOL}: ${tolOk ? 'PASS' : 'FAIL'}`);
console.log(`item selection tie-consistent  : ${selOk ? 'PASS' : 'FAIL'}`);
process.exit(tolOk && selOk ? 0 : 1);
